### ISSUE TITLE
Dockerfile.alpine build error

### ISSUE THREAD

**Issue by hatami57** [isopen/docker#1]
Hi!

When building the `Dockerfile.alpine`, it encounters some errors after about %26 of progress, but if I change the line:
https://github.com/isopen/docker/blob/f239ce5eae2e357b7da57fa6e34253c0fd533507/tdlib/Dockerfile.alpine#L12
to:
`RUN cmake ..`
it successfully build the tdlib. However the `libtdjson.so` file seems kind of large (about 62MB). Was the build for debug mode? because in debian version it's about 16MB with `-DCMAKE_BUILD_TYPE=Release` option.
How can I build it in release mode in alpine?

**Comment by hatami57** [comment]
I've found the solution here: https://github.com/tdlib/td/issues/37
as @levlam said:

> try to disable LTO by commenting line 26 of CMakeLists.txt:
> `#    set(CMAKE_CXX_FLAGS_RELEASE "${CMAKE_CXX_FLAGS_RELEASE} ${CXX_FLAGS_IPO}")
`

**Comment by isopen** [comment]
Thanks.
Also:
td/tdutils/td/utils/port/Stat.cpp:line 50 must be replaced by this
#if defined(_BSD_SOURCE) || defined(_SVID_SOURCE) || _POSIX_C_SOURCE >= 200809L || _XOPEN_SOURCE >= 700 || TD_EMSCRIPTEN || 1

**Comment by hatami57** [comment]
That's right. Thanks.
So I'll close the issue :-)
