### ISSUE TITLE
android

### ISSUE THREAD

**Issue by yknext** [isopen/docker#3]
did you know ho to build android shared lib  *.so ? like gradle conf or ndk build

**Comment by isopen** [comment]
Try using [Prebuilt library for Android](https://core.telegram.org/tdlib/tdlib.zip)
Build instruction https://github.com/tdlib/td/tree/master/example/java
Comments on the topic https://github.com/tdlib/td/issues/77

Docker [jni_on](https://github.com/isopen/docker/blob/master/tdlib/jni_on/Dockerfile.debian)
Next you need using NDK or use a ready-made solution [Prebuilt library for Android](https://core.telegram.org/tdlib/tdlib.zip)

Created temporarily solution: https://github.com/isopen/docker/blob/master/tdlib/jni_on/android_achiev/android.cmake.md
